### ISSUE TITLE
Partnership proposal.

### ISSUE THREAD

**Issue by raidenkkj** [batuhantrkgl/InstaWatcher#1]
I looked at your code and found it very interesting.
I currently have a similar project, check https://github.com/raidenkkj/stalk-ify for more details.
What do you think about us forming a partnership and merging our projects? I'm even thinking about implementing this in an app.

If you are interested, you can contact me on telegram (t.me/raidenkk) and close this issue, thanks!

**Comment by batuhantrkgl** [comment]
Sure, Check PMs! (t.me/batuhantrkglv2)
